services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloudgames-catalog-mssql
    ports:
      - "1434:1433" # porta diferente para evitar conflito local
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SenhaForte123!"
      MSSQL_PID: Developer
    volumes:
      - catalog_mssql_data:/var/opt/mssql
    networks:
      - cloudgames-network
    healthcheck:
      test: ["CMD-SHELL", "(/opt/mssql-tools18/bin/sqlcmd -C -S localhost,1433 -U sa -P \"SenhaForte123!\" -Q \"SELECT 1\" || /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P \"SenhaForte123!\" -Q \"SELECT 1\") || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 70s

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: cloudgames-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - catalog_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - cloudgames-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s

  mongo:
    image: mongo:7.0
    container_name: cloudgames-catalog-mongo
    ports:
      - "27017:27017"
    volumes:
      - catalog_mongo_data:/data/db
    networks:
      - cloudgames-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudgames-catalog-api
    ports:
      - "5063:5063"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5063"

      ConnectionStrings__SetupConnection:   "Server=mssql,1433;Database=master;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;"
      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=dbCatalog;User Id=usuario_app;Password=SenhaForte123!;TrustServerCertificate=True;"
      ConnectionStrings__SqlConnection: "Server=mssql,1433;Database=dbCatalog;User Id=usuario_app;Password=SenhaForte123!;TrustServerCertificate=True;"

      Jwt__Key: "chave-secreta-super-forte-123456"
      Jwt__Issuer: "CloudGamesAPI"
      Jwt__Audience: "CloudGamesAPIClient"

      RabbitMq__HostName: "cloudgames-rabbitmq"
      RabbitMq__Port: "5672"
      RabbitMq__UserName: "guest"
      RabbitMq__Password: "guest"
      RabbitMq__ExchangeName: "cloudgames.topic"

      ServiceBus__ConnectionString: "Endpoint=sb://localhost/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_HERE"
      ServiceBus__QueueNameUserCreated: "user-created"

      Elasticsearch__Uri: "http://elasticsearch:9200"
      MongoDb__ConnectionString: "mongodb://mongo:27017"
      MongoDb__Database: "catalogdb"
      MongoDb__ReviewCollection: "game_reviews"
    depends_on:
      mssql:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys
    networks:
      - cloudgames-network

networks:
  cloudgames-network:
    external: true

volumes:
  catalog_mssql_data:
  dataprotection_keys:
  catalog_elasticsearch_data:
  catalog_mongo_data:
