services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cloudgames-catalog-mssql
    ports:
      - "1434:1433" # porta diferente para evitar conflito local
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SenhaForte123!"
      MSSQL_PID: Developer
    volumes:
      - catalog_mssql_data:/var/opt/mssql
    networks:
      - cloudgames-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudgames-catalog-api
    ports:
      - "5056:5055"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:5055"

      ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=dbCatalog;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;"

      RabbitMq__HostName: "cloudgames-rabbitmq"
      RabbitMq__Port: "5672"
      RabbitMq__UserName: "guest"
      RabbitMq__Password: "guest"
      RabbitMq__ExchangeName: "cloudgames.topic"

    networks:
      - cloudgames-network

networks:
  cloudgames-network:
    external: true

volumes:
  catalog_mssql_data:
