apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  labels:
    app: catalog-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:5063"
  ASPNETCORE_HTTP_PORTS: "5063"
  Jwt__Issuer: "CloudGamesAPI"
  Jwt__Audience: "CloudGamesAPIClient"
  ServiceBus__QueueNameOrderPlaced: "OrderPlacedEvent"
  ServiceBus__QueueNamePaymentProcessed: "PaymentProcessedEvent"
  ServiceBus__SubscriptionPaymentProcessed: "CatalogApi"
  Elasticsearch__Uri: "http://elasticsearch:9200"
  MongoDb__ConnectionString: "mongodb://mongo:27017"
  MongoDb__Database: "catalogdb"
  MongoDb__ReviewCollection: "game_reviews"
