apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
    - name: tcp
      protocol: TCP
      port: 1433
      targetPort: 1433
