apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-api-kv
  labels:
    app: catalog-api
spec:
  provider: azure
  secretObjects:
    - secretName: catalog-api-secret
      type: Opaque
      data:
        - objectName: catalog-ConnectionStrings--SqlConnection
          key: ConnectionStrings__SqlConnection
        - objectName: catalog-Jwt--Key
          key: Jwt__Key
        - objectName: catalog-ServiceBus--ConnectionString
          key: ServiceBus__ConnectionString
        - objectName: catalog-ApplicationInsights--ConnectionString
          key: ApplicationInsights__ConnectionString
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    keyvaultName: "__KEYVAULT_NAME__"
    tenantId: "__AZURE_TENANT_ID__"
    objects: |
      array:
        - |
          objectName: catalog-ConnectionStrings--SqlConnection
          objectType: secret
        - |
          objectName: catalog-Jwt--Key
          objectType: secret
        - |
          objectName: catalog-ServiceBus--ConnectionString
          objectType: secret
        - |
          objectName: catalog-ApplicationInsights--ConnectionString
          objectType: secret
