apiVersion: v1
kind: Secret
metadata:
  name: catalog-api-secret
  labels:
    app: catalog-api
type: Opaque
stringData:
  # JWT Key for authentication (plain text - Kubernetes will store base64)
  Jwt__Key: "chave-secreta-super-forte-123456"
  # RabbitMQ credentials
  RabbitMq__UserName: "guest"
  RabbitMq__Password: "guest"
  # Database connection strings (override `ConnectionStrings` in appsettings)
  ConnectionStrings__DefaultConnection: "Server=mssql,1433;Database=dbCatalog;User Id=usuario_app;Password=SenhaForte123!;TrustServerCertificate=True;"
  ConnectionStrings__SetupConnection: "Server=mssql,1433;Database=master;User Id=sa;Password=SenhaForte123!;TrustServerCertificate=True;"
