apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: catalog-api-kv
  labels:
    app: catalog-api
spec:
  provider: azure
  secretObjects:
    - secretName: catalog-api-secret
      type: Opaque
      data:
        - objectName: ConnectionStrings--SqlConnection
          key: ConnectionStrings__SqlConnection
        - objectName: ConnectionStrings--SetupConnection
          key: ConnectionStrings__SetupConnection
        - objectName: Jwt--Key
          key: Jwt__Key
        - objectName: ServiceBus--ConnectionString
          key: ServiceBus__ConnectionString
        - objectName: ApplicationInsights--ConnectionString
          key: ApplicationInsights__ConnectionString
        - objectName: MongoDb--ConnectionString
          key: MongoDb__ConnectionString
        - objectName: Secrets--Password
          key: Secrets__Password
  parameters:
    useWorkloadIdentity: "true"
    keyvaultName: "__KEYVAULT_NAME__"
    tenantId: "__AZURE_TENANT_ID__"
    clientID: "0052f425-5ecb-40da-acec-30d48c0f8cba"
    objects: |
      array:
        - |
          objectName: ConnectionStrings--SqlConnection
          objectType: secret
        - |
          objectName: ConnectionStrings--SetupConnection
          objectType: secret
        - |
          objectName: Jwt--Key
          objectType: secret
        - |
          objectName: ServiceBus--ConnectionString
          objectType: secret
        - |
          objectName: ApplicationInsights--ConnectionString
          objectType: secret
        - |
          objectName: MongoDb--ConnectionString
          objectType: secret
        - |
          objectName: Secrets--Password
          objectType: secret