apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-api
  labels:
    app: catalog-api
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: "0052f425-5ecb-40da-acec-30d48c0f8cba"